version: '3.1'

services:
  spring-tax:
    build: .
    restart: always
    container_name: spring-tax
    ports:
      - 8080:8080
    working_dir: /opt/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - 27017:27017
    volumes:
      - /data/mongo-db-data:/data/db
      - /data/mongo-db-bkp:/data/bkp
    restart: always